// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vagtplanlægnings_modul.Data;

#nullable disable

namespace Vagtplanlægnings_modul.Migrations.ShiftDb
{
    [DbContext(typeof(ShiftDbContext))]
    [Migration("20260507112101_ShiftCreate")]
    partial class ShiftCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vagtplanlægnings_modul.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Shift_Id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndTime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartTime");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Vagtplanlægnings_modul.Models.ShiftAssignment", b =>
                {
                    b.Property<Guid>("ShiftAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftAssignment_Id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Assigned_At");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeRole_Id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.HasKey("ShiftAssignmentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("Vagtplanlægnings_modul.Models.ShiftRequirement", b =>
                {
                    b.Property<Guid>("ShiftRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftRequirement_Id");

                    b.Property<byte>("Amount")
                        .HasColumnType("tinyint")
                        .HasColumnName("Amount");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role_Id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShiftRequirementId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftRequirements");
                });

            modelBuilder.Entity("Vagtplanlægnings_modul.Models.ShiftAssignment", b =>
                {
                    b.HasOne("Vagtplanlægnings_modul.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Vagtplanlægnings_modul.Models.ShiftRequirement", b =>
                {
                    b.HasOne("Vagtplanlægnings_modul.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
