// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timegrip.Employees.Api.Data;

#nullable disable

namespace Timegrip.Employees.Api.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20260511180824_EmployeeDb")]
    partial class EmployeeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Employee")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timegrip.Employees.Api.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<DateOnly>("HiredAt")
                        .HasColumnType("date")
                        .HasColumnName("hiredAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phoneNr");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("employeeStatus");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees", "Employee");
                });

            modelBuilder.Entity("Timegrip.Employees.Api.Models.Employment", b =>
                {
                    b.Property<Guid>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("int");

                    b.HasKey("EmploymentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Employments", "Employee");
                });

            modelBuilder.Entity("Timegrip.Employees.Api.Models.Employment", b =>
                {
                    b.HasOne("Timegrip.Employees.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
