services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - backend

  bff-api:
    build:
      context: .
      dockerfile: services/Bff.Api/Dockerfile
    container_name: bff-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      FRONTEND_ORIGIN: "http://localhost:62892"
      EMPLOYEES_API_URL: "http://employees-api:8080"
      ROLES_API_URL: "http://roles-api:8080"
      SHIFTS_API_URL: "http://shifts-api:8080"
    ports:
      - "5000:8080"
    depends_on:
      - employees-api
      - roles-api
      - shifts-api
    networks:
      - backend

  employees-api:
    build:
      context: .
      dockerfile: services/Employees.Api/Dockerfile
    container_name: employees-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CONNECTION_STRING: "Server=mssql,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;ConnectRetryCount=0;"
      FRONTEND_ORIGIN: "http://localhost:62892"
    ports:
      - "5001:8080"
    depends_on:
      - mssql
    networks:
      - backend

  roles-api:
    build:
      context: .
      dockerfile: services/Roles.Api/Dockerfile
    container_name: roles-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CONNECTION_STRING: "Server=mssql,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;ConnectRetryCount=0;"
      FRONTEND_ORIGIN: "http://localhost:62892"
    ports:
      - "5002:8080"
    depends_on:
      - mssql
    networks:
      - backend

  shifts-api:
    build:
      context: .
      dockerfile: services/Shifts.Api/Dockerfile
    container_name: shifts-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CONNECTION_STRING: "Server=mssql,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;ConnectRetryCount=0;"
      FRONTEND_ORIGIN: "http://localhost:62892"
    ports:
      - "5003:8080"
    depends_on:
      - mssql
    networks:
      - backend

volumes:
  mssql_data:

networks:
  backend:
