// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timegrip.Shifts.Api.Data;

#nullable disable

namespace Timegrip.Shifts.Api.Migrations
{
    [DbContext(typeof(ShiftsDbContext))]
    [Migration("20260511180347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Shift")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timegrip.Shifts.Api.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Shift_Id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("endTime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startTime");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts", "Shift");
                });

            modelBuilder.Entity("Timegrip.Shifts.Api.Models.ShiftAssignment", b =>
                {
                    b.Property<Guid>("ShiftAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftAssignment_Id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Assigned_At");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employeeRole_Id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shift_Id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.HasKey("ShiftAssignmentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftAssignments", "Shift");
                });

            modelBuilder.Entity("Timegrip.Shifts.Api.Models.ShiftRequirement", b =>
                {
                    b.Property<Guid>("ShiftRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftRequirement_Id");

                    b.Property<byte>("Amount")
                        .HasColumnType("tinyint")
                        .HasColumnName("Amount");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role_Id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShiftRequirementId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftRequirements", "Shift");
                });

            modelBuilder.Entity("Timegrip.Shifts.Api.Models.ShiftAssignment", b =>
                {
                    b.HasOne("Timegrip.Shifts.Api.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Timegrip.Shifts.Api.Models.ShiftRequirement", b =>
                {
                    b.HasOne("Timegrip.Shifts.Api.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
